eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:4040}/eureka

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://${FRONT_HOST:localhost}:${FRONT_PORT:3000}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: MSExploitations
          uri: lb://MSExploitations
          predicates:
            - Path=/exploitations/**
          filters:
            - RewritePath=/exploitations/?(?<lien>.*), /${lien}

        - id: MSSupervision
          uri: lb://MSSupervision
          predicates:
            - Path=/supervision/**
          filters:
            - RewritePath=/supervision/?(?<lien>.*), /${lien}

        - id: MSNotification
          uri: lb://MSNotification
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/?(?<lien>.*), /${lien}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read-only
