# ===============================
# =        APP / PORT           =
# ===============================
spring.application.name=MSNotification
server.port=9097

# ===============================
# =           KAFKA             =
# ===============================
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

spring.kafka.consumer.group-id=ms-notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=tn.itbs.tp.kafka
spring.kafka.consumer.properties.spring.json.value.default.type=tn.itbs.tp.kafka.AlerteEvent
#spring.kafka.consumer.properties.spring.json.use.type.headers=false

# ===============================
# =           DATABASE          =
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/MSNotification?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}

# ===============================
# =           JPA / HIBERNATE   =
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# =           EUREKA CLIENT     =
# ===============================
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:4040}/eureka

# ===============================
# =           ACTUATOR          =
# ===============================
management.endpoints.web.exposure.include=refresh
