spring.application.name=MSTache
server.port=9095

# --- RABBITMQ ---
spring.rabbitmq.addresses=amqps://gwqjwngd:ZFRK5-QHq9iZgZaRT9gAo0aw_ZPWDR-N@gorilla.lmq.cloudamqp.com/gwqjwngd

# --- DATABASE ---
spring.datasource.url=jdbc:mysql://localhost:3306/MSTache?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username={cipher}8fd015711f7d6ce4ac68ec79fed0cee4f9d04c70791bc5551ab9b40182ae4035
spring.datasource.password=

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- EUREKA ---
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:4040/eureka

# --- ACTUATOR / REFRESH ---
management.endpoints.web.exposure.include=refresh
